name: Update GitHub Stats Image

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats with private count
        run: |
          curl "https://github-readme-stats.vercel.app/api/top-langs/?username=hzaun&layout=compact&count_private=true&hide_border=true&show_icons=true" \
            -H "Authorization: token ${{ secrets.GH_STATS_TOKEN }}" \
            -o assets/top-langs.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/top-langs.svg
          git commit -m "🔄 Update stats image" || echo "No changes"
          git push
