name: Update GitHub Stats Image

on:
  workflow_dispatch:    # Allows manual run
  schedule:
    - cron: '0 0 * * *' # Runs every 24 hours at midnight UTC

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create assets directory
        run: mkdir -p assets

      - name: Download GitHub Stats SVG
        run: |
          curl "https://github-readme-stats.vercel.app/api/top-langs/?username=hzaun&layout=compact&count_private=true&hide_border=true&show_icons=true" \
            -H "Authorization: token ${{ secrets.GH_STATS_TOKEN }}" \
            -o assets/top-langs.svg

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/top-langs.svg
          git commit -m "🔄 Update stats image" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main

